### ISSUE TITLE
hi how to run it?

### ISSUE THREAD

**Issue by wintonBy** [puniverse/javafs#1]
i use the shell script to start program,but it seems does not work;

**Comment by pron** [comment]
What happens?

**Comment by btiernay** [comment]
Hey, wondering when this might be released to Maven central. Looks like a pretty sweet project, as I've come to expect from your @pron

**Comment by btiernay** [comment]
Running:

```
git clone https://github.com/puniverse/javafs.git
cd javafs
mkdir /tmp/mnt
./run.sh /tmp/mnt
```

I get this:

```
========================
Mounting filesystem com.google.common.jimfs.JimfsFileSystem@2be94b0f at /tmp/mnt
========================
Sep 29, 2015 8:29:16 PM co.paralleluniverse.javafs.FuseFileSystemProvider beforeMount
INFO: [/private/tmp/mnt] Method succeeded.
Sep 29, 2015 8:29:16 PM co.paralleluniverse.javafs.FuseFileSystemProvider getName
INFO: Method succeeded. Result: com.google.common.jimfs.JimfsFileSystem@2be94b0f
Sep 29, 2015 8:29:16 PM co.paralleluniverse.javafs.FuseFileSystemProvider getOptions
INFO: Method succeeded. Result: null
Exception in thread "main" java.lang.UnsatisfiedLinkError: dlopen(libfuse.dylib, 9): image not found
    at jnr.ffi.provider.jffi.NativeLibrary.loadNativeLibraries(NativeLibrary.java:87)
    at jnr.ffi.provider.jffi.NativeLibrary.getNativeLibraries(NativeLibrary.java:70)
    at jnr.ffi.provider.jffi.NativeLibrary.getSymbolAddress(NativeLibrary.java:49)
    at jnr.ffi.provider.jffi.NativeLibrary.findSymbolAddress(NativeLibrary.java:59)
    at jnr.ffi.provider.jffi.AsmLibraryLoader.generateInterfaceImpl(AsmLibraryLoader.java:117)
    at jnr.ffi.provider.jffi.AsmLibraryLoader.loadLibrary(AsmLibraryLoader.java:59)
    at jnr.ffi.provider.jffi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:43)
    at jnr.ffi.LibraryLoader.load(LibraryLoader.java:287)
    at jnr.ffi.LibraryLoader.load(LibraryLoader.java:266)
    at co.paralleluniverse.fuse.Platform.init(Platform.java:71)
    at co.paralleluniverse.fuse.Platform.fuse(Platform.java:24)
    at co.paralleluniverse.fuse.Fuse.init(Fuse.java:100)
    at co.paralleluniverse.fuse.Fuse.mount(Fuse.java:143)
    at co.paralleluniverse.javafs.JavaFS.mount(JavaFS.java:25)
    at co.paralleluniverse.javafs.Main.main(Main.java:26)
```

Because I read:

> Differences from jnr-fuse: this project supports Java 7 (jnr-fuse supports only Java 8), and more platforms [**(like Mac)**](https://github.com/puniverse/javafs#project-information).

I thought it would work on my Mac:
`uname -a`:

```
Darwin machine.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,3 Darwin
```

**Comment by btiernay** [comment]
After installing https://osxfuse.github.io/ it seemed to work. Sorry, didn't read the README :(

**Comment by pron** [comment]
Well, it's available as `co.paralleluniverse:javafs:0.1.0-SNAPSHOT` on Sonatype's snapshot repository (`https://oss.sonatype.org/content/repositories/snapshots`) which you can add to your build file.

**Comment by btiernay** [comment]
Would you say its ready for prime time? If so, maybe a release can be made.

**Comment by pron** [comment]
I don't know. It certainly hasn't had much testing or usage yet.
